baseURL = "https://indreørn.dk"
languageCode = "da-DK"
theme = "adritian-free-hugo-theme"
title = "Indre ørn"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "css/indre-rn.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Yoga"
  URL = "#yoga"
  weight = 2

  [[menu.header]]
  name = "Lydrejser"
  URL = "#lydrejser"
  weight = 3

  [[menu.header]]
  name = "Ceremonier"
  URL = "#ceremonier"
  weight = 4


  [[menu.footer]]
  name = "Yoga"
  URL = "#yoga-og-meditation"
  weight = 2
  
  [[menu.footer]]
  name = "Lydrejser"
  URL = "#lydrejser"
  weight = 3

  [[menu.footer]]
  name = "Ceremonier"
  URL = "#ceremonier"
  weight = 4


[params]

  #sections = ["showcase", "yoga", "lydrejser", "meditationer", "om-mig", "erfaring", "uddannelse", "kontakt", "newsletter"]
  #sections = ["showcase", "about", "education", "experience", "testimonial"]
  sections = ["showcase", "about", "education", "experience", "lydrejser", "ceremonier"]

  [params.logo]
    text1 = "indre"
    text2 = "ørn"

  [params.footer]
      copyright = "Baseret på Hugo-temaet Adritian"
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
